[package]
name = "sqlake-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
schemars.workspace = true
serde = { workspace = true }
serde_json.workspace = true
sqlake-app.workspace = true
sqlake-config.workspace = true
sqlake-core.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "rt", "time"] }
tracing.workspace = true

[dev-dependencies]
sqlake-driver-mock.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
