[package]
name = "sqlake-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
sqlake-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
sqlake-driver-mock.workspace = true
time = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }
